CREATE DATABASE IF NOT EXISTS lafdb;
USE lafdb;

-- TABLE users
CREATE TABLE users (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
phone VARCHAR(20),
role ENUM('admin','user') NOT NULL DEFAULT 'user',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- TABLE lost_items
CREATE TABLE lost_items (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
item_name VARCHAR(150) NOT NULL,
description TEXT,
category VARCHAR(100),
color VARCHAR(50),
brand VARCHAR(100),
image VARCHAR(255),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- TABLE found_items
CREATE TABLE found_items (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
item_name VARCHAR(150) NOT NULL,
description TEXT,
category VARCHAR(100),
color VARCHAR(50),
brand VARCHAR(100),
image VARCHAR(255),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- TABLE lost_reports
CREATE TABLE lost_reports (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
user_id BIGINT NOT NULL,
lost_item_id BIGINT NOT NULL,
location_lost VARCHAR(255),
date_lost DATE,
description TEXT,
status ENUM('open','found','closed') DEFAULT 'open',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
FOREIGN KEY (lost_item_id) REFERENCES lost_items(id) ON DELETE CASCADE
);

-- TABLE found_reports
CREATE TABLE found_reports (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
user_id BIGINT NOT NULL,
found_item_id BIGINT NOT NULL,
location_found VARCHAR(255),
date_found DATE,
description TEXT,
status ENUM('available','claimed','returned') DEFAULT 'available',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
FOREIGN KEY (found_item_id) REFERENCES found_items(id) ON DELETE CASCADE
);

-- TABLE item_claims
CREATE TABLE item_claims (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
user_id BIGINT NOT NULL,
found_report_id BIGINT NOT NULL,
claim_description TEXT,
proof_image VARCHAR(255),
status ENUM('pending','approved','rejected') DEFAULT 'pending',
approved_by BIGINT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
FOREIGN KEY (found_report_id) REFERENCES found_reports(id) ON DELETE CASCADE,
FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
);